### ISSUE TITLE
remove vendor dir

### ISSUE THREAD

**Issue by chennqqi** [s8sg/faas-flow-consul-statestore#5]
This repo will always be used in `faas-flow` project. 
Common location is <fass-flow project>/vendor/github.com/s8sg/faas-flow-consul-statestore
if <fass-flow project>/handler.go import this repo.
Whthin `dep init`, dep will auto pull this repo's dependency.

if anyone get this project under windows. may cause 'filename too lang' error.

**Comment by s8sg** [comment]
@chennqqi go `sdk` need to provide the right dependency. vendor are there to make sure the right dependency is present.  If there is  a change in dependency or issue, the vendor need to be updated
